# Dependencies & build settings
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-feed
  - jekyll-paginate


# Setup
title:            self.boost
tagline:          SWE Resource Reviews
description:      >-
  A review source on various software books, tutorials, and guides
baseurl:          ''
url:              'https://wilkinsb.github.io'

author:
  name:            'Brandon Wilkins'
  email:           brandwilki@gmail.com
  url:             https://github.com/wilkinsb
  github_username: wilkinsb

paginate:         5

github:
  repo:           https://github.com/wilkinsb/wilkinsb.github.io
